apps/trend_following_web/lib/trend_following_web/router.ex
defmodule TrendFollowingWeb.Router do
  use TrendFollowingWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_session do
    plug Guardian.Plug.Pipeline, module: TrendFollowingWeb.Helpers.Guardian
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource, allow_blank: true
    plug TrendFollowingWeb.Helpers.CurrentUser
  end

  pipeline :browser_required_signin do
    plug Guardian.Plug.Pipeline, module: TrendFollowingWeb.Helpers.Guardian,
      error_handler: TrendFollowingWeb.Helpers.AuthErrorHandler
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug TrendFollowingWeb.Helpers.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TrendFollowingWeb do
    pipe_through [:browser, :browser_session]

    get "/", PageController, :index
    
    get "/signup", UserController, :new
    post "/signup", UserController, :create

    get "/signin", SessionController, :new
    post "/signin", SessionController, :create

    resources "/password_reset", PasswordResetController, only: [:show, :create, :update], singleton: true
  end

  scope "/", TrendFollowingWeb do
    pipe_through [:browser, :browser_required_signin] # Use the default browser stack

    delete "/signout", SessionController, :delete

    get "/settings", SettingController, :index
    resources "/settings/:page", SettingController, only: [:show, :update], singleton: true

    resources "/market", MarketController, singleton: true, only: [:show] do
      resources "/CN_Stocks", CNStockController, param: "symbol", only: [:index, :show] do
        get "/position", PositionController, :show
        get "/backtest", BacktestController, :show
      end
      
      resources "/HK_Stocks", HKStockController, param: "symbol", only: [:index, :show] do
        get "/position", PositionController, :show
        get "/backtest", BacktestController, :show
      end

      resources "/US_Stocks", USStockController, param: "symbol", only: [:index, :show] do
        get "/position", PositionController, :show
        get "/backtest", BacktestController, :show
      end

      resources "/I_Futures", IFutureController, param: "symbol", only: [:index, :show] do
        get "/position", PositionController, :show
        get "/backtest", BacktestController, :show
      end

      resources "/G_Futures", GFutureController, param: "symbol", only: [:index, :show] do
        get "/position", PositionController, :show
        get "/backtest", BacktestController, :show
      end
    end
  end

  scope "/api" do
    # pipe_through [:graphql]

    forward "/", Absinthe.Plug,
      schema: TrendFollowingWeb.Graphql.Schema
  end

  scope "/graphiql" do
    forward "/", Absinthe.Plug.GraphiQL,
      schema: TrendFollowingWeb.Graphql.Schema
  end

  # Other scopes may use custom stacks.
  # scope "/api", TrendFollowingWeb do
  #   pipe_through :api
  # end
end

apps/trend_following_web/lib/trend_following_web/controllers/cn_stock_controller.ex
defmodule TrendFollowingWeb.CNStockController do
  use TrendFollowingWeb, :controller

  alias TrendFollowing.Markets

  def index(conn, params) do
    market =
      case Map.get(params, "tab", "all") do
        "all" -> :cn
        "bull" -> :cn_bull
        "bear" -> :cn_bear
      end

    page = Markets.stock_paginate(market, params)

    conn
    |> assign(:title, "沪深")
    |> assign(:params, params)
    |> assign(:page, page)
    |> render(:index)
  end

  def show(conn, %{"symbol" => symbol}) do
    stock = Markets.get_stock!(symbol)

    js_config = %{
      symbol: symbol,
      trend: Markets.trend(stock.dayk),
    }

    conn
    |> assign(:title, stock.cname)
    |> assign(:stock, stock)
    |> assign(:js_config, js_config)
    |> render(:show)
  end
end

apps/trend_following_web/lib/trend_following_web/views/cn_stock_view.ex
defmodule TrendFollowingWeb.CNStockView do
  use TrendFollowingWeb, :view

  def tabs_data(conn) do
    [
      {"全部", "all", market_cn_stock_path(conn, :index, tab: "all")},
      {"适合做多的", "bull", market_cn_stock_path(conn, :index, tab: "bull")},
      {"适合做空的", "bear", market_cn_stock_path(conn, :index, tab: "bear")},
    ]
  end
end

apps/trend_following_web/lib/trend_following_web/templates/cn_stock/index.html.eex
<div class="columns">
  <div class="column is-2">
    <%= render TrendFollowingWeb.MarketView, "panel.html", assigns %>
  </div>
  <div class="column">
    <%= render TrendFollowingWeb.MarketView, "tabs.html", data: tabs_data(@conn), params: @params %>
    <div class="columns">
      <div class="column">
        <nav class="breadcrumb" aria-label="breadcrumbs">
          <ul>
            <li><a>共 <%= @page.total_entries %> 条记录</a></li>
            <li><a>共 <%= @page.total_pages %> 页</a></li>
            <li><a>当前第 <%= @page.page_number %> 页</a></li>
          </ul>
        </nav>
      </div>
      <div class="column">
        <form>
          <div class="field has-addons has-addons-right">
            <%= if Map.get(@params, "tab") do %>
            <input type="hidden" name="tab" value="<%= Map.get(@params, "tab") %>">
            <% end %>
            <p class="control">
              <input class="input" type="text" name="q" placeholder="股票代码或公司名称" value="<%= Map.get(@params, "q", "")%>">
            </p>
            <p class="control">
              <button class="button is-primary">
                搜索
              </button>
            </p>
          </div>
        </form>
      </div>
    </div>
    <div>
      <table class="table is-bordered is-striped is-narrow is-fullwidth">
        <tr>
          <th>代码</th>
          <th>名称</th>
          <th>最新价</th>
          <th>涨跌额</th>
          <th>涨跌幅</th>
          <th>振幅</th>
          <th>昨收/今开盘</th>
          <th>最高价/最低价</th>
          <th>成交量</th>
          <th>市值</th>
          <th>市盈率</th>
          <th>操作</th>
        </tr>
        <%= for stock <- @page do %>
        <tr>
          <td>
            <%= link to: market_cn_stock_path(@conn, :show, stock.symbol), target: "_blank" do %>
              <%= stock.symbol %>
            <% end %>
          </td>
          <td>
            <%= link to: market_cn_stock_path(@conn, :show, stock.symbol), target: "_blank" do %>
              <%= stock.cname |> truncate(length: 14) %>
            <% end %>
          </td>
          <td><%= stock.dayk.close %></td>
          <td><%= stock.dayk |> diff() %></td>
          <td><%= stock.dayk |> chg() %>%</td>
          <td><%= stock.dayk |> amplitude() %>%</td>
          <td><%= stock.dayk.pre_close %>/<%= stock.dayk.open %></td>
          <td><%= stock.dayk.high %>/<%= stock.dayk.low %></td>
          <td><%= stock.dayk |> number_human(:volume) %></td>
          <td><%= stock |> number_human(:market_cap) %></td>
          <td><%= stock.pe |> number_round() %></td>
          <td>
            <div class="dropdown is-right is-hoverable">
              <div class="dropdown-trigger">
                <button class="button is-danger is-small" aria-haspopup="true">
                  
                  <span class="icon is-small">
                    <i class="fa fa-angle-down" aria-hidden="true"></i>
                  </span>
                </button>
              </div>
              <div class="dropdown-menu" role="menu">
                <div class="dropdown-content">
                  <div class="dropdown-item">
                    <%= stock.cname %> (<%= stock.symbol %>)
                  </div>
                  <hr class="dropdown-divider">
                  <%= link "查看详情", to: market_cn_stock_path(@conn, :show, stock.symbol), class: "dropdown-item" %>
                  <%= link "头寸方案", to: market_cn_stock_position_path(@conn, :show, stock.symbol), class: "dropdown-item" %>
                  <%= link "回测情况", to: market_cn_stock_backtest_path(@conn, :show, stock.symbol), class: "dropdown-item" %>
                </div>
              </div>
            </div>
          </td>
        </tr>
        <% end %>
      </table>
      <%= if @page.total_pages > 1 do %>
        <%= pagination_links @page, to_keyword(@params) |> Keyword.drop([:page]) %>
      <% end %>
    </div>
  </div>
</div>

apps/trend_following_web/lib/trend_following_web/templates/cn_stock/show.html.eex
<div class="columns">
  <div class="column is-8">
    <div>
      <strong style="font-size: 24px;">
        <%= @stock.cname %> 
        <%= @stock.symbol %>
      </strong>
      <%= link "头寸方案", to: market_cn_stock_position_path(@conn, :show, @stock.symbol), class: "button is-small is-primary", target: "_blank" %>
      <%= link "回测情况", to: market_cn_stock_backtest_path(@conn, :show, @stock.symbol), class: "button is-small is-info", target: "_blank" %>
    </div>
  </div>
  <div class="column" style="padding-top: 20px;"> 
    <span id="stock-star-btn" class="is-pulled-right"></span>
    <span id="stock-backlist-btn" class="is-pulled-right" style="margin-right: 20px;"></span>
  </div>
</div>

<div class="columns">
  <div class="column is-9">
    <!-- React Component: StockChart  -->
    <div id="k-chart"></div>
    <div id="slider"></div>
  </div>
  <div class="column is-3">
    <div id="stock-detail-cn"></div>
  </div>
</div>