apps/trend_following_web/lib/trend_following_web/router.ex
defmodule TrendFollowingWeb.Router do
  use TrendFollowingWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_session do
    plug Guardian.Plug.Pipeline, module: TrendFollowingWeb.Helpers.Guardian
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource, allow_blank: true
    plug TrendFollowingWeb.Helpers.CurrentUser
  end

  pipeline :browser_required_signin do
    plug Guardian.Plug.Pipeline, module: TrendFollowingWeb.Helpers.Guardian,
      error_handler: TrendFollowingWeb.Helpers.AuthErrorHandler
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug TrendFollowingWeb.Helpers.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TrendFollowingWeb do
    pipe_through [:browser, :browser_session]

    get "/", PageController, :index
    
    get "/signup", UserController, :new
    post "/signup", UserController, :create

    get "/signin", SessionController, :new
    post "/signin", SessionController, :create

    resources "/password_reset", PasswordResetController, only: [:show, :create, :update], singleton: true
  end

  scope "/", TrendFollowingWeb do
    pipe_through [:browser, :browser_required_signin] # Use the default browser stack

    delete "/signout", SessionController, :delete

    get "/settings", SettingController, :index
    resources "/settings/:page", SettingController, only: [:show, :update], singleton: true

    resources "/market", MarketController, singleton: true, only: [:show] do
      resources "/CN_Stocks", CNStockController, param: "symbol", only: [:index, :show] do
        get "/position", PositionController, :show
        get "/backtest", BacktestController, :show
      end
      
      resources "/HK_Stocks", HKStockController, param: "symbol", only: [:index, :show] do
        get "/position", PositionController, :show
        get "/backtest", BacktestController, :show
      end

      resources "/US_Stocks", USStockController, param: "symbol", only: [:index, :show] do
        get "/position", PositionController, :show
        get "/backtest", BacktestController, :show
      end

      resources "/I_Futures", IFutureController, param: "symbol", only: [:index, :show] do
        get "/position", PositionController, :show
        get "/backtest", BacktestController, :show
      end

      resources "/G_Futures", GFutureController, param: "symbol", only: [:index, :show] do
        get "/position", PositionController, :show
        get "/backtest", BacktestController, :show
      end
    end
  end

  scope "/api" do
    # pipe_through [:graphql]

    forward "/", Absinthe.Plug,
      schema: TrendFollowingWeb.Graphql.Schema
  end

  scope "/graphiql" do
    forward "/", Absinthe.Plug.GraphiQL,
      schema: TrendFollowingWeb.Graphql.Schema
  end

  # Other scopes may use custom stacks.
  # scope "/api", TrendFollowingWeb do
  #   pipe_through :api
  # end
end

apps/trend_following_web/lib/trend_following_web/controllers/i_future_controller.ex
defmodule TrendFollowingWeb.IFutureController do
  use TrendFollowingWeb, :controller

  alias TrendFollowing.Markets

  def index(conn, params) do
    market =
      case Map.get(params, "tab", "all") do
        "all" -> :i
        "bull" -> :i_bull
        "bear" -> :i_bear
      end

    data = Markets.list_future(market)

    conn
    |> assign(:title, "国内期货")
    |> assign(:data, data)
    |> assign(:params, params)
    |> render(:index)
  end

  def show(conn, %{"symbol" => symbol}) do
    future = Markets.get_future(symbol)

    js_config = %{
      symbol: symbol,
      trend: Markets.trend(future.dayk),
    }

    conn
    |> assign(:title, future.name)
    |> assign(:future, future)
    |> assign(:js_config, js_config)
    |> render(:show)
  end
end

apps/trend_following_web/lib/trend_following_web/views/i_future_view.ex
defmodule TrendFollowingWeb.IFutureView do
  use TrendFollowingWeb, :view

  def tabs_data(conn) do
    [
      {"全部", "all", market_i_future_path(conn, :index, tab: "all")},
      {"适合做多的", "bull", market_i_future_path(conn, :index, tab: "bull")},
      {"适合做空的", "bear", market_i_future_path(conn, :index, tab: "bear")},
    ]
  end
end

apps/trend_following_web/lib/trend_following_web/templates/i_future/index.html.eex
<div class="columns">
  <div class="column is-2">
    <%= render TrendFollowingWeb.MarketView, "panel.html", assigns %>
  </div>
  <div class="column">
    <%= render TrendFollowingWeb.MarketView, "tabs.html", data: tabs_data(@conn), params: @params %>  
    <div>
      <table class="table is-bordered is-striped is-narrow is-fullwidth">
        <tr>
          <th>代码</th>
          <th>名称</th>
          <th>最新价</th>
          <th>涨跌额</th>
          <th>涨跌幅</th>
          <th>振幅</th>
          <th>昨收/今开盘</th>
          <th>最高价/最低价</th>
          <th>成交量</th>
          <th>操作</th>
        </tr>
        <%= for future <- @data do %>
        <tr>
          <td>
            <%= link to: market_i_future_path(@conn, :show, future.symbol), target: "_blank" do %>
              <%= future.symbol %>
            <% end %>
          </td>
          <td>
            <%= link to: market_i_future_path(@conn, :show, future.symbol), target: "_blank" do %>
              <%= future.name |> truncate(length: 14) %>
            <% end %>
          </td>
          <td><%= future.dayk.close %></td>
          <td><%= future.dayk |> diff() %></td>
          <td><%= future.dayk |> chg() %>%</td>
          <td><%= future.dayk |> amplitude() %>%</td>
          <td><%= future.dayk.pre_close |> float_to_string(2) %>/<%= future.dayk.open |> float_to_string(2) %></td>
          <td><%= future.dayk.high |> float_to_string(2) %>/<%= future.dayk.low |> float_to_string(2) %></td>
          <td><%= future.dayk |> number_human(:volume) %></td>
          <td>
            <div class="dropdown is-right is-hoverable">
              <div class="dropdown-trigger">
                <button class="button is-danger is-small" aria-haspopup="true">
                  
                  <span class="icon is-small">
                    <i class="fa fa-angle-down" aria-hidden="true"></i>
                  </span>
                </button>
              </div>
              <div class="dropdown-menu" role="menu">
                <div class="dropdown-content">
                  <div class="dropdown-item">
                    <%= future.name %> (<%= future.symbol %>)
                  </div>
                  <hr class="dropdown-divider">
                  <%= link "查看详情", to: market_i_future_path(@conn, :show, future.symbol), class: "dropdown-item" %>
                  <%= link "头寸方案", to: market_i_future_position_path(@conn, :show, future.symbol), class: "dropdown-item" %>
                  <%= link "回测情况", to: market_i_future_backtest_path(@conn, :show, future.symbol), class: "dropdown-item" %>
                </div>
              </div>
            </div>
          </td>
        </tr>
        <% end %>
      </table>

    </div>
  </div>
</div>

apps/trend_following_web/lib/trend_following_web/templates/i_future/show.html.eex
<div class="columns">
  <div class="column is-8">
    <div>
      <strong style="font-size: 24px;">
        <%= @future.name %> 
        <%= @future.symbol %>
      </strong>
      <%= link "头寸方案", to: market_i_future_position_path(@conn, :show, @future.symbol), class: "button is-small is-primary", target: "_blank" %>
      <%= link "回测情况", to: market_i_future_backtest_path(@conn, :show, @future.symbol), class: "button is-small is-info", target: "_blank" %>
    </div>
  </div>
  <div class="column" style="padding-top: 20px;"> 
    <span id="future-star-btn" class="is-pulled-right"></span>
    <span id="future-backlist-btn" class="is-pulled-right" style="margin-right: 20px;"></span>
  </div>
</div>

<div class="columns">
  <div class="column is-9">
    <!-- React Component: futureChart  -->
    <div id="k-chart"></div>
    <div id="slider"></div>
  </div>
  <div class="column is-3">
    <div id="future-detail-i"></div>
  </div>
</div>